name: Call WOWCAM Deno /scrape endpoint

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call WOWCAM Deno /scrape endpoint
        run: |
          curl -fsS "https://wowcam.deno.dev/scrape?token=${{ secrets.WOWCAM_TOKEN }}"
